#pragma once
#ifndef MAIN_H
#define MAIN_H

#include "path.h"       // will be generated by CMake
#include "version.h"    // will be generated by CMake

#include <iostream>
#include <regex>    // std::regex
#include <string>   // std::string, std::stoi
#include <vector>

extern int exit;

#include "array_handler.h"
#include "menu.h"
#include "search_binary.h"
#include "sort_by_bubble.h"

#endif // MAIN_H